Repository zeabur/zbpack, pull requests merged in 2023-10, with the labels that each got.

#161 feat(planner/static): Support hugo configuration directory mode & test case
  internal/static/identify.go
  tests/static-hugo-config-dir/archetypes/default.md
  tests/static-hugo-config-dir/config/_default/hugo.toml
  tests/static-hugo-config-dir/public/categories/index.xml
  tests/static-hugo-config-dir/public/index.xml
  tests/static-hugo-config-dir/public/sitemap.xml
  tests/static-hugo-config-dir/public/tags/index.xml
Labels: improvement

#163 fix: change python base image version
  internal/python/python.go
Labels: python

#171 ZEA-2126: Exclude hidden dir in static provider
  internal/static/TransformServerless.go
  pkg/zeaburpack/image.go
Labels: bug
