Repository zeabur/zbpack, pull requests merged in 2023-06, with the labels that each got.

#84 feat(cli): Check Docker daemon status before start
  cmd/zbpack/main.go
  go.mod
  go.sum
Labels: improvement

#88 refactor(cli): Use the Cobra framework to enhance CLI
  README.md
  cmd/zbpack/main.go
  cmd/zbpack/main_test.go
  cmd/zbplan/main.go
  go.mod
  go.sum
  internal/zbpack/helper.go
  internal/zbpack/zbpack.go
Labels: enhancement

#93 feat(planner/elixir): Add Elixir support
  internal/elixir/elixir.go
  internal/elixir/elixir_test.go
  internal/elixir/identify.go
  internal/elixir/identify_test.go
  internal/elixir/plan.go
  internal/elixir/plan_test.go
  internal/elixir/templates/template.Dockerfile
  pkg/types/plan.go
  pkg/zeaburpack/identifiers.go
  pkg/zeaburpack/packers.go
  tests/elixir-cases/elixir/README.md
  tests/elixir-cases/elixir/assets/css/app.css
  tests/elixir-cases/elixir/assets/css/phoenix.css
  tests/elixir-cases/elixir/assets/js/app.js
  tests/elixir-cases/elixir/assets/vendor/topbar.js
  tests/elixir-cases/elixir/config/config.exs
  tests/elixir-cases/elixir/config/dev.exs
  tests/elixir-cases/elixir/config/prod.exs
  tests/elixir-cases/elixir/config/runtime.exs
  tests/elixir-cases/elixir/config/test.exs
  tests/elixir-cases/elixir/lib/elixir_no_ecto.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto/application.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto/mailer.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/controllers/page_controller.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/endpoint.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/gettext.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/router.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/telemetry.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/templates/layout/app.html.heex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/templates/layout/live.html.heex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/templates/layout/root.html.heex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/templates/page/index.html.heex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/views/error_helpers.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/views/error_view.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/views/layout_view.ex
  tests/elixir-cases/elixir/lib/elixir_no_ecto_web/views/page_view.ex
  tests/elixir-cases/elixir/mix.exs
  tests/elixir-cases/elixir/mix.lock
  tests/elixir-cases/elixir/priv/gettext/en/LC_MESSAGES/errors.po
  tests/elixir-cases/elixir/priv/gettext/errors.pot
  tests/elixir-cases/elixir/priv/static/favicon-a8ca4e3a2bb8fea46a9ee9e102e7d3eb.ico
  tests/elixir-cases/elixir/priv/static/favicon.ico
  tests/elixir-cases/elixir/priv/static/images/phoenix-5bd99a0d17dd41bc9d9bf6840abcc089.png
  tests/elixir-cases/elixir/priv/static/images/phoenix.png
  tests/elixir-cases/elixir/priv/static/robots-9e2c81b0855bbff2baa8371bc4a78186.txt
  tests/elixir-cases/elixir/priv/static/robots-9e2c81b0855bbff2baa8371bc4a78186.txt.gz
  tests/elixir-cases/elixir/priv/static/robots.txt
  tests/elixir-cases/elixir/priv/static/robots.txt.gz
  tests/elixir-cases/elixir_ecto/README.md
  tests/elixir-cases/elixir_ecto/config/config.exs
  tests/elixir-cases/elixir_ecto/lib/friends.ex
  tests/elixir-cases/elixir_ecto/lib/friends/application.ex
  tests/elixir-cases/elixir_ecto/lib/friends/person.ex
  tests/elixir-cases/elixir_ecto/lib/friends/repo.ex
  tests/elixir-cases/elixir_ecto/mix.exs
  tests/elixir-cases/elixir_ecto/mix.lock
  tests/elixir-cases/elixir_ecto/priv/repo/migrations/20220831094119_create_people.exs
  tests/elixir-cases/elixir_ecto/priv/repo/seeds.exs
Labels: enhancement, gssoc, gssoc23, level2
