Repository zeabur/zbpack, pull requests merged in 2023-09, with the labels that each got.

#133 fix(planner/nodejs): Fix build failed when need puppeteer and no build script
  internal/nodejs/plan.go
Labels: bug

#135 feat(lib): Serverless output for static websites and Next.js
  go.mod
  go.sum
  internal/nodejs/__snapshots__/template_test.snap
  internal/nodejs/nextjs/function.go
  internal/nodejs/nextjs/launcher.go
  internal/nodejs/nextjs/launcher.js.tmpl
  internal/nodejs/nextjs/main.go
  internal/nodejs/node.go
  internal/nodejs/node_test.go
  internal/nodejs/plan.go
  internal/nodejs/template_test.go
  internal/nodejs/templates/nginx-runtime.Dockerfile
  internal/nodejs/templates/template.Dockerfile
  internal/static/TransformServerless.go
  internal/utils/copy_from_image.go
  pkg/types/config.go
  pkg/zeaburpack/main.go
Labels: enhancement

#136 fix(planner/python): Install pkg-config by default
  internal/python/plan.go
Labels: python

#137 feat(planner/nodejs): Add nuejs support
  internal/nodejs/plan.go
  pkg/types/plan.go
Labels: enhancement

#142 feat(planner/bun): Support Bao.js
  internal/bun/plan.go
  pkg/types/plan.go
Labels: enhancement

#143 feat: support bagel
  internal/bun/plan.go
  pkg/types/plan.go
Labels: enhancement
