Repository zeabur/zbpack, pull requests merged in 2024-02, with the labels that each got.

#207 fix(planner/python): Add start command prefix to Django collectstatic
  internal/python/plan.go
Labels: bug

#208 feat(planner/rust): Implement rust serverless
  .gitignore
  internal/rust/identify.go
  internal/rust/plan.go
  internal/rust/rust.go
  internal/rust/template.Dockerfile
  pkg/zeaburpack/main.go
Labels: enhancement

#210 fix(plan/rust): Fix file missing due to rust build binary name
  internal/rust/template.Dockerfile
Labels: bug

#211 ZEA-2569: Refactor PHP extension installer
  internal/php/__snapshots__/template_test.snap
  internal/php/identify.go
  internal/php/php.go
  internal/php/plan.go
  internal/php/template_test.go
Labels: bug, enhancement

#212 fix(plan/rust): Fix rust compile binary rename
  internal/rust/template.Dockerfile
Labels: bug

#213 ZEA-2581: install php extensions
  internal/php/__snapshots__/template_test.snap
  internal/php/php.go
Labels: bug

#214 fix(planner/python): Matched ) is not required
  internal/python/plan.go
  internal/python/plan_test.go
Labels: bug

#216 feat(planner/java): Support custom Java argument
  internal/java/identify.go
  internal/java/java.go
Labels: enhancement
